language: python
dist: xenial
python:
    - "3.6"
install:
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
script:
    - nosetests -v
notifications:
    email:
        - zmcx16@gmail.com